package com.ais_db.enums;

public enum AddOnType {
    ZERO_DEPRECIATION,
    ROAD_SIDE_ASSISTANCE,
    ENGINE_PROTECTION,
    CONSUMABLES_COVER,
    RETURN_TO_INVOICE,
    KEY_REPLACEMENT,
    PERSONAL_ACCIDENT,
    PASSENGER_COVER,
    NCB_PROTECTION,
    TYRE_PROTECTION,
    WINDSHIELD_COVER
}
